-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointments
(
    appointment_id serial NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'scheduled'::character varying,
    created_by integer,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    notes text COLLATE pg_catalog."default",
    CONSTRAINT appointments_pkey PRIMARY KEY (appointment_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    log_id serial NOT NULL,
    user_id integer,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    record_id integer,
    "timestamp" timestamp without time zone NOT NULL DEFAULT now(),
    details text COLLATE pg_catalog."default",
    CONSTRAINT audit_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.billing
(
    billing_id serial NOT NULL,
    patient_id integer NOT NULL,
    appointment_id integer,
    amount numeric(10, 2) NOT NULL,
    payment_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'unpaid'::character varying,
    insurance_provider character varying(100) COLLATE pg_catalog."default",
    insurance_claim_id character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT billing_pkey PRIMARY KEY (billing_id)
);

CREATE TABLE IF NOT EXISTS public.doctors
(
    doctor_id serial NOT NULL,
    user_id integer,
    specialty character varying(100) COLLATE pg_catalog."default",
    license_number character varying(50) COLLATE pg_catalog."default",
    contact_info text COLLATE pg_catalog."default",
    last_login_at timestamp without time zone,
    CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id),
    CONSTRAINT doctors_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.medical_records
(
    record_id serial NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer,
    visit_date date NOT NULL,
    diagnosis text COLLATE pg_catalog."default",
    treatment_notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_at timestamp without time zone,
    visibility character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'normal'::character varying,
    CONSTRAINT medical_records_pkey PRIMARY KEY (record_id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    patient_id serial NOT NULL,
    user_id integer,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dob date,
    contact_info text COLLATE pg_catalog."default",
    last_login_at timestamp without time zone,
    CONSTRAINT patients_pkey PRIMARY KEY (patient_id),
    CONSTRAINT patients_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.pharmacists
(
    pharmacist_id serial NOT NULL,
    user_id integer,
    can_dispense boolean NOT NULL DEFAULT true,
    CONSTRAINT pharmacists_pkey PRIMARY KEY (pharmacist_id),
    CONSTRAINT pharmacists_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.prescriptions
(
    prescription_id serial NOT NULL,
    record_id integer NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer,
    pharmacist_id integer,
    drug_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    dosage character varying(100) COLLATE pg_catalog."default" NOT NULL,
    frequency character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'issued'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    dispensed_at timestamp without time zone,
    CONSTRAINT prescriptions_pkey PRIMARY KEY (prescription_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    last_login_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id)
    REFERENCES public.doctors (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.billing
    ADD CONSTRAINT billing_appointment_id_fkey FOREIGN KEY (appointment_id)
    REFERENCES public.appointments (appointment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.billing
    ADD CONSTRAINT billing_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.doctors
    ADD CONSTRAINT doctors_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS doctors_user_id_key
    ON public.doctors(user_id);


ALTER TABLE IF EXISTS public.medical_records
    ADD CONSTRAINT medical_records_doctor_id_fkey FOREIGN KEY (doctor_id)
    REFERENCES public.doctors (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.medical_records
    ADD CONSTRAINT medical_records_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT patients_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS patients_user_id_key
    ON public.patients(user_id);


ALTER TABLE IF EXISTS public.pharmacists
    ADD CONSTRAINT pharmacists_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pharmacists_user_id_key
    ON public.pharmacists(user_id);


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id)
    REFERENCES public.doctors (doctor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT prescriptions_pharmacist_id_fkey FOREIGN KEY (pharmacist_id)
    REFERENCES public.pharmacists (pharmacist_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT prescriptions_record_id_fkey FOREIGN KEY (record_id)
    REFERENCES public.medical_records (record_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;